# Generated by Django 3.1 on 2020-09-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20200912_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
