# Generated by Django 3.1 on 2020-09-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_history_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='object_id',
        ),
    ]
